### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/infografia-de-las-librerias-NoeliaGlez#3]
[Librerías.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-NoeliaGlez/files/8882336/Librerias.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by Litzy-lopez4** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
